# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=<%= ruby_version %>
FROM registry.docker.com/library/ruby:$RUBY_VERSION

WORKDIR /rails

# Install packages needed to build gems and node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev node-gyp pkg-config python-is-python3

# Install JavaScript dependencies
<% if using_bun? -%>
ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=<%= dockerfile_bun_version %>
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"
<% else -%>
ARG NODE_VERSION=<%= dockerfile_node_version %>
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    rm -rf /tmp/node-build-master
<% if js_package_manager == :yarn -%>
ARG YARN_VERSION=<%= dockerfile_yarn_version %>
<% if yarn_through_corepack? -%>
RUN corepack enable && corepack install -g yarn@$YARN_VERSION
<% else -%>
RUN npm install -g yarn@$YARN_VERSION
<% end -%>
<% elsif js_package_manager == :pnpm -%>
RUN corepack enable && corepack install -g pnpm@latest
<% end -%>
<% end -%>

# Additional dependencies go here

# Upgrade RubyGems and install the latest Bundler version
RUN gem update --system && gem install bundler

# Document that we're going to expose port 3000
EXPOSE 3000
# Use Bash as the default command
CMD ["/bin/bash"]
