# plutonium.rbs
module Plutonium
  class Error < StandardError; end

  def self.root: () -> Pathname
  def self.lib_root: () -> Pathname
  def self.logger: () -> Logger
  def self.application_name: () -> String
  def self.application_name=: (String) -> void
  def self.development?: () -> bool
  def self.eager_load_rails!: () -> void
end
